/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfazPostulante;

/**
 *
 * @author Windows 11 Pro
 */
public class FacultadCarrera extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FacultadCarrera.class.getName());

    /**
     * Creates new form FacultadCarrera
     */
    public FacultadCarrera() {
        initComponents();
        this.setSize(800, 540);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        Titulo = new javax.swing.JLabel();
        FacultadSeleccionada = new javax.swing.JComboBox<>();
        TituloFacultad = new javax.swing.JLabel();
        TituloCarrera = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        Seleccion = new javax.swing.JLabel();
        CarreraSeleccionada = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(800, 500));

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Titulo.setBackground(new java.awt.Color(255, 255, 255));
        Titulo.setFont(new java.awt.Font("Segoe UI Black", 0, 36)); // NOI18N
        Titulo.setForeground(new java.awt.Color(255, 255, 255));
        Titulo.setText("Seleccione su Facultad Y Carrera");
        jPanel2.add(Titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 50, -1, -1));

        FacultadSeleccionada.setMaximumRowCount(50);
        FacultadSeleccionada.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ciencias Económicas", "Ciencias y Tecnología", "Humanidades y Ciencias de la Educación", "Ciencias Jurídicas y Politicas", "Arquitectura y Ciencias del Hábitad", "Medicina", "Bioquímica y Farmacia", "Odontologia", "Ciencias Agricolas y Pecuarias", "Veterinaria", "Ciencias Sociales", "Facultad Politecnica del Valle Alto", "Enfermeria", "Desarrollo Rural y Territorial" }));
        FacultadSeleccionada.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        FacultadSeleccionada.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                FacultadSeleccionadaItemStateChanged(evt);
            }
        });
        jPanel2.add(FacultadSeleccionada, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 230, 290, -1));

        TituloFacultad.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        TituloFacultad.setForeground(new java.awt.Color(255, 255, 255));
        TituloFacultad.setText("Seleccione su Facultad :");
        jPanel2.add(TituloFacultad, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 230, 320, -1));

        TituloCarrera.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        TituloCarrera.setForeground(new java.awt.Color(255, 255, 255));
        TituloCarrera.setText("Seleccione su Carerra :");
        jPanel2.add(TituloCarrera, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 340, 310, -1));
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 260, 700, 10));
        jPanel2.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 370, 700, 10));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        Seleccion.setBackground(new java.awt.Color(255, 255, 255));
        Seleccion.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        Seleccion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Seleccion.setText("Seleccionado");
        Seleccion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Seleccion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SeleccionMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Seleccion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Seleccion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 430, 140, 30));

        CarreraSeleccionada.setMaximumRowCount(50);
        CarreraSeleccionada.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Licenciatura en Economía", "Licenciatura en Administración de Empresas", "Licenciatura en Contaduría Pública", "Licenciatura en Ingenieria Comercial", "Licenciatura en Ingenieria Financiera" }));
        CarreraSeleccionada.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel2.add(CarreraSeleccionada, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 340, 290, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Postulantes-a-la-Universidad\\src\\ImagenesDeInterfaces\\FacultadCarrera\\paseoUniversitarioFN.jpg")); // NOI18N
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 500));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void FacultadSeleccionadaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_FacultadSeleccionadaItemStateChanged

    if (evt.getStateChange() == java.awt.event.ItemEvent.SELECTED) {
        String facultadSeleccionada = (String) FacultadSeleccionada.getSelectedItem();
        CarreraSeleccionada.removeAllItems();
            switch (facultadSeleccionada) {
                
                case "Ciencias Económicas" -> {
                    CarreraSeleccionada.addItem("Licenciatura en Economía");
                    CarreraSeleccionada.addItem("Licenciatura en Administración de Empresas");
                    CarreraSeleccionada.addItem("Licenciatura en Contaduría Pública");
                    CarreraSeleccionada.addItem("Licenciatura en Ingenieria Comercial");
                    CarreraSeleccionada.addItem("Licenciatura en Ingenieria Financiera");
                }

                case "Ciencias y Tecnología" -> {
                    CarreraSeleccionada.addItem("Ingeniería Civil");
                    CarreraSeleccionada.addItem("Ingeniería de Alimentos");
                    CarreraSeleccionada.addItem("Ingeniería de Sistemas");
                    CarreraSeleccionada.addItem("Ingeniería Eléctrica");
                    CarreraSeleccionada.addItem("Ingeniería Electrónica");
                    CarreraSeleccionada.addItem("Ingeniería Electromecanica");
                    CarreraSeleccionada.addItem("Ingeniería Industrial");
                    CarreraSeleccionada.addItem("Ingeniería en Informatica");
                    CarreraSeleccionada.addItem("Ingeniería Matemática");
                    CarreraSeleccionada.addItem("Ingeniería Mecánica");
                    CarreraSeleccionada.addItem("Ingeniería Química");
                    CarreraSeleccionada.addItem("Programa de Ingeniería en Biotecnologia");
                    CarreraSeleccionada.addItem("Programa de Ingeniería en Energía");
                    CarreraSeleccionada.addItem("Licenciatura en Biologia");
                    CarreraSeleccionada.addItem("Licenciatura en Didáctica de la Física");
                    CarreraSeleccionada.addItem("Licenciatura en Didáctica de la Matemática");
                    CarreraSeleccionada.addItem("Licenciatura en Física");
                    CarreraSeleccionada.addItem("Licenciatura en Matemáticas");
                    CarreraSeleccionada.addItem("Licenciatura en Química");
                }

                case "Humanidades y Ciencias de la Educación" -> {
                    CarreraSeleccionada.addItem("Licenciatura en Psicología");
                    CarreraSeleccionada.addItem("Licenciatura en Ciencias de la Educación");
                    CarreraSeleccionada.addItem("Licenciatura en Lingüística Aplicada a la Enseñanza de Lenguas");
                    CarreraSeleccionada.addItem("Licenciatura en Comunicación Social");
                    CarreraSeleccionada.addItem("Licenciatura en Trabajo Social");
                    CarreraSeleccionada.addItem("Licenciatura en Música");
                    CarreraSeleccionada.addItem("Licenciatura en Cs. de la Actividad Fisica y del Deporte");
                    CarreraSeleccionada.addItem("Licenciatura en Educación Intercultural Bilingüe");
                }

                case "Ciencias Jurídicas y Politicas" -> {
                    CarreraSeleccionada.addItem("Licenciatura en Ciencias Jurídicas");
                    CarreraSeleccionada.addItem("Licenciatura en Ciencias Políticas");
                }

                case "Arquitectura y Ciencias del Hábitad" -> {
                    CarreraSeleccionada.addItem("Licenciatura en Arquitectura");
                    CarreraSeleccionada.addItem("Licenciatura en Diseño Gráfico y Comunicación Visual");
                    CarreraSeleccionada.addItem("Licenciatura en Planificación del Territorio y Medio Ambiente");
                    CarreraSeleccionada.addItem("Licenciatura en Turismo");
                    CarreraSeleccionada.addItem("Técnico Universitario Superior en Construcciones");
                    CarreraSeleccionada.addItem("Técnico Universitario Superior en Diseño de Interiores y del Mobiliario");
                }

                case "Medicina" -> {
                    CarreraSeleccionada.addItem("Licenciatura en Medicina");
                    CarreraSeleccionada.addItem("Licenciatura en Fisioterapia y Kinesiología");
                    CarreraSeleccionada.addItem("Licenciatura en Nutrición y Dietética");
                    CarreraSeleccionada.addItem("Licenciatura en Ciencias Jurídicas");
                }

                case "Bioquímica y Farmacia" -> {
                    CarreraSeleccionada.addItem("Licenciatura en Bioquímica y Farmacia");
                }

                case "Odontologia" -> {
                    CarreraSeleccionada.addItem("Licenciatura en Odontologia");
                }

                case "Ciencias Agricolas y Pecuarias" -> {
                    CarreraSeleccionada.addItem("Ingeniería Agronómica");
                    CarreraSeleccionada.addItem("Ingeniería Agroindustrial");
                    CarreraSeleccionada.addItem("Ingeniería Agrícola");
                    CarreraSeleccionada.addItem("Ingeniería Fitotecnista");
                    CarreraSeleccionada.addItem("Ingeniería Zootecnista");
                }

                case "Veterinaria" -> {
                    CarreraSeleccionada.addItem("Medicina Veterinaria y Zootecnia");
                }

                case "Ciencias Sociales" -> {
                    CarreraSeleccionada.addItem("Licenciatura en Sociología");
                    CarreraSeleccionada.addItem("Programa de Licenciatura en Antropología");
                }

                case "Facultad Politecnica del Valle Alto" -> {
                    CarreraSeleccionada.addItem("Técnico Universitario Superior en Construcción Civil");
                    CarreraSeleccionada.addItem("Programa Complementario de Licenciatura en Mecánica Automotriz y Maquinaria Agroindustrial");
                    CarreraSeleccionada.addItem("Técnico Universitario Superior en Mecánica Automotriz");
                    CarreraSeleccionada.addItem("Técnico Universitario Superior en Mecánica Industrial");
                    CarreraSeleccionada.addItem("Técnico Universitario Superior en Química Industrial");
                    CarreraSeleccionada.addItem("Técnico Universitario Superior en Industria de Alimentos");
                    CarreraSeleccionada.addItem("Técnico Universitario Medio en Enfermería");
                }

                case "Desarrollo Rural y Territorial" -> {
                    CarreraSeleccionada.addItem("Carrera de Tecnico Superior en Agronomia");
                    CarreraSeleccionada.addItem("Licenciatura en Produccion Agraria y Desarrollo Territorial");
                }

                case "Enfermeria" -> {
                    CarreraSeleccionada.addItem("Licenciatura en Enfermería");
                }
            }
        
    }
    }//GEN-LAST:event_FacultadSeleccionadaItemStateChanged

    private void SeleccionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SeleccionMouseClicked
           String facultadSeleccionada = (String) FacultadSeleccionada.getSelectedItem();
           String carreraSeleccionada = (String) CarreraSeleccionada.getSelectedItem();
           
            //aqui le ponen a guardar la facultad y carrera seleccionada
    }//GEN-LAST:event_SeleccionMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FacultadCarrera().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CarreraSeleccionada;
    private javax.swing.JComboBox<String> FacultadSeleccionada;
    private javax.swing.JLabel Seleccion;
    private javax.swing.JLabel Titulo;
    private javax.swing.JLabel TituloCarrera;
    private javax.swing.JLabel TituloFacultad;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    // End of variables declaration//GEN-END:variables
}
