/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package paqueteInterfacesPostulantes;

import javax.swing.JOptionPane;
import paqueteServicios.Postulante;
import paqueteServicios.RegistroDocumentacion;
import paqueteServicios.consultaPostulante;

/**
 *
 * @author Windows 11 Pro
 */
public class EstadoInscripcion extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(EstadoInscripcion.class.getName());
     private Postulante objPostulante;
     private RegistroDocumentacion objRegistroDocumentacion;
    // 2. Debiste recibirlo en el constructor de esta clase
    /**
     * Creates new form EstadoInscripcion
     */
    public EstadoInscripcion(Postulante postulante) {
    initComponents();
    this.objPostulante = postulante;
    cargarDatosPostulante();
    
    /*
    actualizarCheckBachiller(true);
    actualizarCheckCI(true);
    actualizarCheckPago(true);
    mensajeExito();
    Nombre.setText("Oli");
    Apellido.setText("Pampañaupa");
    CI.setText("8645353");
    Facultad.setText("Ciencias Economicas");
    Carrera.setText("Lic.en Contaduria");
    Correo.setText("oli@gmail.com");
    Fecha.setText("15/08/2004");
    */
}

private void cargarDatosPostulante() {
    if (objPostulante != null) {
        Nombre.setText(objPostulante.getStrNombre());
        Apellido.setText(objPostulante.getStrApellido());
        CI.setText(objPostulante.getStrNumeroCI());
        Fecha.setText(objPostulante.getStrFechaNacimiento());

        if (objPostulante.getObjRegistroDocumentacion() != null) {
            objRegistroDocumentacion = objPostulante.getObjRegistroDocumentacion();
            Carrera.setText(objRegistroDocumentacion.getStrCarrera() != null ? objRegistroDocumentacion.getStrCarrera() : "No seleccionada");
            Facultad.setText(objRegistroDocumentacion.getStrFacultad() != null ? objRegistroDocumentacion.getStrFacultad() : "No seleccionada");
            Correo.setText(objPostulante.getStrCorreoElectronico());

            actualizarCheckCI(objPostulante.getStrNumeroCI() != null && !objPostulante.getStrNumeroCI().isEmpty());
            actualizarCheckBachiller(objRegistroDocumentacion.getStrCodigoCertificadoPromo() != null && !objRegistroDocumentacion.getStrCodigoCertificadoPromo().isEmpty());
            actualizarCheckPago(objRegistroDocumentacion.getBolEstadoDePago());
        } else {
            Carrera.setText("No seleccionada");
            Facultad.setText("No seleccionada");
            Correo.setText(objPostulante.getStrCorreoElectronico());
            actualizarCheckCI(false);
            actualizarCheckBachiller(false);
            actualizarCheckPago(false);
        }
        mensajeExito();
    } else {
        JOptionPane.showMessageDialog(
            this,
            "No se pudo cargar el postulante.",
            "Error",
            JOptionPane.ERROR_MESSAGE
        );
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator3 = new javax.swing.JSeparator();
        CheckCI = new javax.swing.JLabel();
        MensajeCI = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        Correo = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Nombre = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Apellido = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        CI = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        Fecha = new javax.swing.JLabel();
        Carrera = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        Facultad = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        CheckPago = new javax.swing.JLabel();
        CheckBachiller = new javax.swing.JLabel();
        MensajePago = new javax.swing.JLabel();
        MensajeBachiller = new javax.swing.JLabel();
        MensajeExito = new javax.swing.JLabel();
        Retroceder = new javax.swing.JLabel();
        Actualizar = new javax.swing.JLabel();

        CheckCI.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes de interfaces/EstadoInscripcion/Check.png"))); // NOI18N

        MensajeCI.setBackground(new java.awt.Color(51, 51, 51));
        MensajeCI.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        MensajeCI.setForeground(new java.awt.Color(102, 102, 102));
        MensajeCI.setText("jLabel24");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(1920, 1080));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes de interfaces/EstadoInscripcion/PielogoUMSS.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 880, 1920, 190));

        jPanel2.setBackground(new java.awt.Color(196, 95, 95));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 0, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Postulante :");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 360, 60));
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 93, 380, 10));

        Correo.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        Correo.setForeground(new java.awt.Color(255, 255, 255));
        Correo.setText("paquito@gmail.com");
        jPanel2.add(Correo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 560, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Nombre :");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));

        Nombre.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        Nombre.setForeground(new java.awt.Color(255, 255, 255));
        Nombre.setText("Paquito");
        jPanel2.add(Nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Apellido :");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, -1, -1));

        Apellido.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        Apellido.setForeground(new java.awt.Color(255, 255, 255));
        Apellido.setText("Eleuterio ");
        jPanel2.add(Apellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("CI :");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, -1, -1));

        CI.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        CI.setForeground(new java.awt.Color(255, 255, 255));
        CI.setText("6545654");
        jPanel2.add(CI, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, -1, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Fecha de Nacimiento :");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 420, -1, -1));

        Fecha.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        Fecha.setForeground(new java.awt.Color(255, 255, 255));
        Fecha.setText("14/05/2004");
        jPanel2.add(Fecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 450, -1, -1));

        Carrera.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        Carrera.setForeground(new java.awt.Color(255, 255, 255));
        Carrera.setText("Lic. en contaduria");
        jPanel2.add(Carrera, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 760, -1, -1));

        jLabel13.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Correo Electronico :");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 530, -1, -1));

        jLabel14.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Facultad :");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 630, -1, -1));

        Facultad.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        Facultad.setForeground(new java.awt.Color(255, 255, 255));
        Facultad.setText("Ciencias Economicas");
        jPanel2.add(Facultad, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 660, -1, -1));

        jLabel16.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Carrera :");
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 730, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1530, 0, 380, 880));

        jLabel17.setFont(new java.awt.Font("Segoe UI Black", 0, 62)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 55, 130));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("Estado de Inscripcion");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 10, 680, -1));

        jLabel18.setFont(new java.awt.Font("Segoe UI Black", 0, 36)); // NOI18N
        jLabel18.setText("Pago de Valorado :");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 630, 450, -1));

        jLabel19.setFont(new java.awt.Font("Segoe UI Black", 0, 36)); // NOI18N
        jLabel19.setText("Titulo de Bachiller :");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 290, 450, -1));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 333, 950, 10));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 680, 950, 20));

        CheckPago.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes de interfaces/EstadoInscripcion/Uncheck.png"))); // NOI18N
        jPanel1.add(CheckPago, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 640, 40, 40));

        CheckBachiller.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes de interfaces/EstadoInscripcion/Uncheck.png"))); // NOI18N
        jPanel1.add(CheckBachiller, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 290, 40, 40));

        MensajePago.setBackground(new java.awt.Color(51, 51, 51));
        MensajePago.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        MensajePago.setForeground(new java.awt.Color(102, 102, 102));
        MensajePago.setText("jLabel24");
        jPanel1.add(MensajePago, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 650, -1, -1));

        MensajeBachiller.setBackground(new java.awt.Color(51, 51, 51));
        MensajeBachiller.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        MensajeBachiller.setForeground(new java.awt.Color(102, 102, 102));
        MensajeBachiller.setText("jLabel24");
        jPanel1.add(MensajeBachiller, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 300, -1, -1));

        MensajeExito.setFont(new java.awt.Font("Segoe UI Black", 0, 36)); // NOI18N
        MensajeExito.setForeground(new java.awt.Color(0, 153, 0));
        jPanel1.add(MensajeExito, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 470, -1, -1));

        Retroceder.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes de interfaces/EstadoInscripcion/Retroceder.png"))); // NOI18N
        Retroceder.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RetrocederMouseClicked(evt);
            }
        });
        jPanel1.add(Retroceder, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 110, 120));

        Actualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes de interfaces/EstadoInscripcion/Actualizar.png"))); // NOI18N
        Actualizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ActualizarMouseClicked(evt);
            }
        });
        jPanel1.add(Actualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 0, 90, 110));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1910, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1070, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RetrocederMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RetrocederMouseClicked
         Menu menuVentana = new Menu(this.objPostulante, this.objRegistroDocumentacion);
         menuVentana.setVisible(true); 
         this.dispose();  
    }//GEN-LAST:event_RetrocederMouseClicked

    private void ActualizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ActualizarMouseClicked
        actualizarEstado();
    }//GEN-LAST:event_ActualizarMouseClicked

    /**
     * @param args the command line arguments
     */
    private void actualizarMensajeBachiller(boolean estado){
       if(estado){
            MensajeBachiller.setText("");           
       }else{
           MensajeBachiller.setText("datos no coinciden, aproximese a oficinas!");
       }
       
    }
    private void actualizarMensajeCI(boolean estado){
       if(estado){
            MensajeCI.setText("");           
       }else{
           MensajeCI.setText("datos no coinciden, aproximese a oficinas!");
       }
       
    }
    private void actualizarMensajePago(boolean estado){
       if(estado){
            MensajePago.setText("");           
       }else{
           MensajePago.setText("Pago no realizado!");
       }
    }
       private void actualizarCheckBachiller(boolean estado){
       if(estado){
            CheckBachiller.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes de interfaces/EstadoInscripcion/Check.png")));
       }else{
           CheckBachiller.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes de interfaces/EstadoInscripcion/UnCheck.png")));
       }
       actualizarMensajeBachiller(estado);
    }
    private void actualizarCheckCI(boolean estado){
       if(estado){
            CheckCI.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes de interfaces/EstadoInscripcion/Check.png")));
       }else{
           CheckCI.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes de interfaces/EstadoInscripcion/UnCheck.png")));
       }
       actualizarMensajeCI(estado);
    }
    private void actualizarCheckPago(boolean estado){
       if(estado){
            CheckPago.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes de interfaces/EstadoInscripcion/Check.png")));
       }else{
           CheckPago.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes de interfaces/EstadoInscripcion/UnCheck.png")));
       }
       actualizarMensajePago(estado);
    }
  private void mensajeExito(){
    if(MensajeBachiller.getText().equals("")&&MensajePago.getText().equals("")){
        MensajeExito.setText("Usted está habilitado! :)");
    }else{
    MensajeExito.setText("");
    }
    }
  private void actualizarEstado() {
    if (objPostulante != null) {
        consultaPostulante consulta = new consultaPostulante();
        Postulante postulanteActualizado = consulta.obtenerPostulanteActualizado(objPostulante);
        if (postulanteActualizado != null) {
            objPostulante = postulanteActualizado;
            objRegistroDocumentacion = objPostulante.getObjRegistroDocumentacion();
        }
        cargarDatosPostulante();
        mensajeExito();
    }
}



    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
       // java.awt.EventQueue.invokeLater(() -> new EstadoInscripcion(postulante).setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Actualizar;
    private javax.swing.JLabel Apellido;
    private javax.swing.JLabel CI;
    private javax.swing.JLabel Carrera;
    private javax.swing.JLabel CheckBachiller;
    private javax.swing.JLabel CheckCI;
    private javax.swing.JLabel CheckPago;
    private javax.swing.JLabel Correo;
    private javax.swing.JLabel Facultad;
    private javax.swing.JLabel Fecha;
    private javax.swing.JLabel MensajeBachiller;
    private javax.swing.JLabel MensajeCI;
    private javax.swing.JLabel MensajeExito;
    private javax.swing.JLabel MensajePago;
    private javax.swing.JLabel Nombre;
    private javax.swing.JLabel Retroceder;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    // End of variables declaration//GEN-END:variables
}
