/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package paqueteInterfacesPostulantes;

import java.awt.Color;
import javax.swing.JFrame;

/**
 *
 * @author Windows 11 Pro
 */
public class MenuMejorado extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MenuMejorado.class.getName());

    /**
     * Creates new form MenuMejorado
     */
    public MenuMejorado() {
        initComponents();
        //this.setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        botonSalir = new javax.swing.JLabel();
        botonMetodosDePago = new javax.swing.JLabel();
        botonEstadoDeInscripcion = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1600, 815));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(1920, 1060));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 57, 117));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes de interfaces/Menu/logoUmssDorado.png"))); // NOI18N
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 130, 130));

        jLabel3.setFont(new java.awt.Font("Segoe UI Black", 0, 60)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Menú Principal");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 20, 530, 90));

        botonSalir.setFont(new java.awt.Font("Segoe UI Black", 0, 36)); // NOI18N
        botonSalir.setForeground(new java.awt.Color(239, 184, 16));
        botonSalir.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        botonSalir.setText("Salir");
        botonSalir.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        botonSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonSalirMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botonSalirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botonSalirMouseExited(evt);
            }
        });
        jPanel2.add(botonSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 620, 430, 80));

        botonMetodosDePago.setFont(new java.awt.Font("Segoe UI Black", 0, 36)); // NOI18N
        botonMetodosDePago.setForeground(new java.awt.Color(239, 184, 16));
        botonMetodosDePago.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        botonMetodosDePago.setText("Métodos de Pago");
        botonMetodosDePago.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        botonMetodosDePago.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonMetodosDePago.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonMetodosDePagoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botonMetodosDePagoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botonMetodosDePagoMouseExited(evt);
            }
        });
        jPanel2.add(botonMetodosDePago, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 250, 430, 80));

        botonEstadoDeInscripcion.setFont(new java.awt.Font("Segoe UI Black", 0, 36)); // NOI18N
        botonEstadoDeInscripcion.setForeground(new java.awt.Color(239, 184, 16));
        botonEstadoDeInscripcion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        botonEstadoDeInscripcion.setText("Estado De Inscripción");
        botonEstadoDeInscripcion.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        botonEstadoDeInscripcion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonEstadoDeInscripcion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonEstadoDeInscripcionMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botonEstadoDeInscripcionMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botonEstadoDeInscripcionMouseExited(evt);
            }
        });
        jPanel2.add(botonEstadoDeInscripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 440, 430, 80));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes de interfaces/Menu/salir.png"))); // NOI18N
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 590, 100, 100));

        jPanel3.setBackground(new java.awt.Color(239, 184, 16));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 820, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 0, 30, 820));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes de interfaces/Menu/metodoPago.png"))); // NOI18N
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 240, 100, 100));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes de interfaces/Menu/estado.png"))); // NOI18N
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 420, 100, 100));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes de interfaces/Menu/paseoUmssPrueba.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 0, 620, 820));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1600, 815));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1600, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 815, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonMetodosDePagoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonMetodosDePagoMouseEntered
       botonMetodosDePago.setForeground(new Color(255, 224,23));
    }//GEN-LAST:event_botonMetodosDePagoMouseEntered

    private void botonMetodosDePagoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonMetodosDePagoMouseExited
        botonMetodosDePago.setForeground(new Color(239,184,16));
    }//GEN-LAST:event_botonMetodosDePagoMouseExited

    private void botonEstadoDeInscripcionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonEstadoDeInscripcionMouseEntered
         botonEstadoDeInscripcion.setForeground(new Color(255, 224,23));
    }//GEN-LAST:event_botonEstadoDeInscripcionMouseEntered

    private void botonEstadoDeInscripcionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonEstadoDeInscripcionMouseExited
        botonEstadoDeInscripcion.setForeground(new Color(239,184,16));
    }//GEN-LAST:event_botonEstadoDeInscripcionMouseExited

    private void botonSalirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonSalirMouseEntered
         botonSalir.setForeground(new Color(255, 224,23));
    }//GEN-LAST:event_botonSalirMouseEntered

    private void botonSalirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonSalirMouseExited
        botonSalir.setForeground(new Color(239,184,16));
    }//GEN-LAST:event_botonSalirMouseExited

    private void botonMetodosDePagoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonMetodosDePagoMouseClicked
        // aqui lo que hara al darle click
    }//GEN-LAST:event_botonMetodosDePagoMouseClicked

    private void botonEstadoDeInscripcionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonEstadoDeInscripcionMouseClicked
        // aqui lo que hara al darle click
    }//GEN-LAST:event_botonEstadoDeInscripcionMouseClicked

    private void botonSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonSalirMouseClicked
        // aqui lo que hara al darle click
    }//GEN-LAST:event_botonSalirMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MenuMejorado().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel botonEstadoDeInscripcion;
    private javax.swing.JLabel botonMetodosDePago;
    private javax.swing.JLabel botonSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
