/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package paqueteInterfacesPostulantes;

import java.awt.Color;
import javax.swing.BorderFactory;
import javax.swing.JFrame;

/**
 *
 * @author Windows 11 Pro
 */
public class MetodoDePagoMejorado extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MetodoDePagoMejorado.class.getName());

    /**
     * Creates new form MetodoDePagoMejorado
     */
    public MetodoDePagoMejorado() {
        initComponents();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        botonBanco = new javax.swing.JLabel();
        botonQR = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        botonConfirmar = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel13 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jPanel3 = new javax.swing.JPanel();
        Retroceder = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 57, 117));
        jPanel1.setPreferredSize(new java.awt.Dimension(1920, 1060));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        botonBanco.setBackground(new java.awt.Color(0, 57, 117));
        botonBanco.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        botonBanco.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes de interfaces/metodos de pago/pagoBanco.png"))); // NOI18N
        botonBanco.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        botonBanco.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonBanco.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonBancoMouseClicked(evt);
            }
        });
        jPanel1.add(botonBanco, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 370, 280, 280));

        botonQR.setBackground(new java.awt.Color(0, 57, 117));
        botonQR.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        botonQR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes de interfaces/metodos de pago/pagoQR.png"))); // NOI18N
        botonQR.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        botonQR.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonQR.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonQRMouseClicked(evt);
            }
        });
        jPanel1.add(botonQR, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 370, 280, 280));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 0, 85)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Metodos de Pago");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 0, 780, 150));

        jPanel2.setBackground(new java.awt.Color(183, 13, 30));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes de interfaces/metodos de pago/LogoUmssAzul-removebg-preview.png"))); // NOI18N
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 370, 370));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes de interfaces/metodos de pago/hombre.png"))); // NOI18N
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 750, 220, 250));

        jLabel9.setFont(new java.awt.Font("Segoe UI Black", 0, 27)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel9.setText("\nun metodo de pago");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 540, 280, 50));

        jLabel8.setFont(new java.awt.Font("Segoe UI Black", 0, 27)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel8.setText("Por favor seleccione\n");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 480, 280, 40));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes de interfaces/metodos de pago/burrbuja (1).png"))); // NOI18N
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 380, 380, 340));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1410, 0, 520, 1060));

        jLabel7.setFont(new java.awt.Font("Segoe UI Black", 0, 48)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(239, 184, 16));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Pago Online ");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 650, 470, -1));

        botonConfirmar.setBackground(new java.awt.Color(183, 13, 30));
        botonConfirmar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonConfirmarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botonConfirmarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botonConfirmarMouseExited(evt);
            }
        });
        botonConfirmar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 0, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Confirmar");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonConfirmar.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 460, 70));

        jPanel1.add(botonConfirmar, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 880, 460, 70));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 720, 470, 20));

        jLabel13.setFont(new java.awt.Font("Segoe UI Black", 0, 48)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(239, 184, 16));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Deposito Bancario");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 650, 470, -1));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 720, 470, 20));

        jPanel4.setBackground(new java.awt.Color(239, 184, 16));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1380, 0, 30, 1060));

        jLabel3.setFont(new java.awt.Font("Segoe UI Black", 0, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(239, 184, 16));
        jLabel3.setText("Monto Total : 350 Bs");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 190, 430, 60));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 1350, 30));

        jPanel3.setBackground(new java.awt.Color(239, 184, 16));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 30, 1060));

        Retroceder.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes de interfaces/metodos de pago/Retroceder.png"))); // NOI18N
        Retroceder.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Retroceder.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RetrocederMouseClicked(evt);
            }
        });
        jPanel1.add(Retroceder, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonBancoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonBancoMouseClicked
        botonBanco.setBackground(new Color(255,255,255));
        botonQR.setBackground(new Color(0,57,117));

    }//GEN-LAST:event_botonBancoMouseClicked

    private void botonQRMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonQRMouseClicked
        botonQR.setBackground(new Color(255,255,255));
        botonBanco.setBackground(new Color(0,57,117));
        
    }//GEN-LAST:event_botonQRMouseClicked

    private void botonConfirmarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonConfirmarMouseEntered
        botonConfirmar.setBackground(new Color(204, 14, 33));
    }//GEN-LAST:event_botonConfirmarMouseEntered

    private void botonConfirmarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonConfirmarMouseExited
        botonConfirmar.setBackground(new Color(183,13,30));
    }//GEN-LAST:event_botonConfirmarMouseExited

    private void botonConfirmarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonConfirmarMouseClicked
        // aqui lo que hara cuando selecciones un metodo de pago y le des a confirmar
    }//GEN-LAST:event_botonConfirmarMouseClicked

    private void RetrocederMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RetrocederMouseClicked
        //aqui que retroceda al menu
    }//GEN-LAST:event_RetrocederMouseClicked

   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MetodoDePagoMejorado().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Retroceder;
    private javax.swing.JLabel botonBanco;
    private javax.swing.JPanel botonConfirmar;
    private javax.swing.JLabel botonQR;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    // End of variables declaration//GEN-END:variables
}
